### ISSUE TITLE
rubocop-emacs doesn't work via tramp

### ISSUE THREAD

**Issue by ojab** [bbatsov/rubocop-emacs#12]
There is actually two issues, but they're closely related:
1. rubocop-emacs is checking rubocop installation on local machine, so we'll get 'RuboCop is not installed' if it isn't installed locally
2. rubocop-emacs uses buffer-file-name, so rubocop is run like `rubocop --format emacs /ssh:notebook:smth.rb`. Filename should be translated before call (something like [this](http://erlang.org/pipermail/erlang-patches/2013-August/004228.html))

**Comment by bbatsov** [comment]
Patches welcome! :-)
