### ISSUE TITLE
Complains that rubocop is not installed when bundling with `--path`

### ISSUE THREAD

**Issue by imtayadeway** [bbatsov/rubocop-emacs#17]
I'd noticed that flycheck hasn't been giving me rubocop feedback for a while. Just tracked this down - it's because when I `bundle install` I use the `--path` flag to put my gems in `vendor/bundle`. Hence, if I want to run the executable `rubocop` in my project I have to run `bundle exec rubocop`. rubocop mode doesn't know this, however, and will simply not run with flycheck. Only on invoking something like `M-x rubocop-check-current-file` will it complain that rubocop is not installed.

I realized that I can work around this by installing rubocop using my current Ruby with `gem install rubocop` i.e. outside of bundler. Of course, I would have preferred it if it had Just Worked.

If this seems like an issue you'd like addressed I'd be happy to tackle it. Thanks!

**Comment by imtayadeway** [comment]
@bbatsov anything I can do to help bring this to some resolution?

**Comment by bbatsov** [comment]
Won't customising `rubocop-check-command` solve your problem? You can set it via a `.dir-locals.el` file just for the projects you want to use `bundle exec rubocop`.

**Comment by imtayadeway** [comment]
I have tried playing around with that before. Adding it now (and removing the rubocop gem and hence executable from my PATH) results in "RuboCop is not installed" when invoking `rubocop-check-current-file`, etc., however I can `bundle exec rubocop` in my shell successfully. Doing `M-: rubocop-check-command` reveals that I have set it correctly and displays `bundle exec rubocop`

**Comment by bbatsov** [comment]
Maybe `exec-path` is not properly set in Emacs. See if you can run `bundle exec rubocop` from `M-!`. If not, you can take a look at `exec-path-from-shell` https://github.com/purcell/exec-path-from-shell.

**Comment by imtayadeway** [comment]
That works as expected - I'm using `exec-path-from-shell`

**Comment by edebill** [comment]
I have rubocop installed to /usr/local/bin on my El Capitan Mac (installed with rvm use system; sudo gem install rubocop).

I persistently get this problem. I fixed it with:

```
(require 'rubocop)
(setq rubocop-check-command "/usr/local/bin/rubocop --format emacs")
(defun rubocop-ensure-installed () )
```

**Comment by imtayadeway** [comment]
@bbatsov it looks like [this function](https://github.com/bbatsov/rubocop-emacs/blob/master/rubocop.el#L143-L146) is short-circuiting some of the commands because it explicitly can't find `rubocop` in `exec-path`. Is there any way this could be changed to optionally check if rubocop has been bundled?

**Comment by bbatsov** [comment]
We can always check the command to do both checks. PRs welcome. :-)

**Comment by imtayadeway** [comment]
@bbatsov thanks! I will try to tackle this in the coming week
