### ISSUE TITLE
[Feature Request] Rspec support

### ISSUE THREAD

**Issue by idoo** [bbatsov/rubocop-emacs#22]
Is it good option to add dynamic support for `rubocop-rspec`? With
```
--require rubocop-rspec
```
Or some parameter for configurate it?
Now I can see only one solution — overwrite `rubocop-check-command` and `rubocop-autocorrect-command` and it's looks for me like monkey patching 🐒

**Comment by bbatsov** [comment]
Yeah, probably we should introduce some extra `defcustom` - a list of extensions to be required.

**Comment by idoo** [comment]
@bbatsov  thank you! 🎉
