### ISSUE TITLE
Include/Exclude relative pathing

### ISSUE THREAD

**Issue by johnfoley3** [bbatsov/rubocop-emacs#24]
Rubocop the binary can be run in any directory, where it walks up the directories until `.rubocop.yml` is found, and it works and all is good. Except for the include and exclude paths, which are relative blobs from the directory that is being run in.

```
Exclude
  'spec/**/*.spec'
```

This will for example work at top level, but if you are one level down in a sibling of `spec/` then the excludes do not work. Flycheck and this Rubocop extension both fall victim to this, and it's fairly annoying. Running `rubocop-check-current-file` doesn't respect excludes all the time and `rubocop-check-project` from a child project directory does not either.

I believe a simple fix is to add something not as gross as `cd (rubocop-project-root) &&` to the `check-command` var, but I could be doing this whole thing wrong or this solution not as good as something else. Any thoughts are appreciated!

**Comment by bbatsov** [comment]
So, just to be clear, you're suggesting that we always run `rubocop` from the root of the current project?

**Comment by johnfoley3** [comment]
Yep, although I'm not confident that I understand the issue comprehensively since no one else has seem to come across this. Do you only run those checking commands at the root directory relative to the `.rubocop.yml`?

**Comment by bbatsov** [comment]
So far the compilation commands were simply executed from the `default-directory`, I've changed this to prefer the project root (when available).
